export const BUSINESS_INFO = {
  name: "FixNow Mechanics",
  phone: "07354 915941",
  email: "fixnowmechanics@outlook.com",
  address: "Hemel Hempstead, HP2 7DE",
  hours: {
    weekday: "Mon-Sat: 7am - 10pm",
    weekend: "Sun: 8am - 8pm",
  },
  coverage: "45-mile radius",
  whatsapp: "https://wa.me/447354915941",
} as const;

export const SERVICES = [
  {
    id: "mobile-diagnostic",
    name: "Mobile Diagnostic",
    description: "Full OBD diagnostic scan, visual inspection, and written report explaining what we find.",
    price: "From £45",
    icon: "Monitor",
    category: "Diagnostics",
  },
  {
    id: "pre-purchase",
    name: "Pre-Purchase Inspection",
    description: "Comprehensive 40-point inspection before you buy a used car. Includes diagnostic scan and detailed report.",
    price: "From £85",
    icon: "Monitor",
    category: "Diagnostics",
  },
  {
    id: "health-check",
    name: "Basic Health Check",
    description: "Quick inspection of fluids, tyres, lights, and battery. Ideal before a long journey.",
    price: "From £35",
    icon: "Monitor",
    category: "Diagnostics",
  },
  {
    id: "interim-service",
    name: "Interim Service",
    description: "Recommended every 6 months or 6,000 miles. Includes oil, filter, and 30-point safety inspection.",
    price: "From £110",
    icon: "Settings",
    category: "Servicing",
  },
  {
    id: "full-service",
    name: "Full Service",
    description: "Annual service with comprehensive 50-point inspection. Includes all filters and service book stamp.",
    price: "From £150",
    icon: "Settings",
    category: "Servicing",
  },
  {
    id: "brake-pads",
    name: "Brake Pad Replacement",
    description: "Quality brake pad fitting with disc and calliper inspection.",
    price: "From £90",
    icon: "CircleDot",
    category: "Brakes",
  },
  {
    id: "brake-pads-discs",
    name: "Brake Pads and Discs",
    description: "Complete brake refresh including new pads and discs.",
    price: "From £160",
    icon: "CircleDot",
    category: "Brakes",
  },
  {
    id: "brake-fluid",
    name: "Brake Fluid Change",
    description: "Full brake fluid flush and replacement.",
    price: "£55",
    icon: "CircleDot",
    category: "Brakes",
  },
  {
    id: "battery",
    name: "Battery Replacement",
    description: "Battery test, fitting new battery, terminal cleaning, and proper disposal.",
    price: "From £100",
    icon: "Zap",
    category: "Electrical",
  },
  {
    id: "general",
    name: "General Repairs",
    description: "Labour rate £45 per hour. We handle all types of mechanical work.",
    price: "Quote",
    icon: "Wrench",
    category: "General",
  },
] as const;

export const LOCATIONS = [
  {
    slug: "hemel-hempstead",
    name: "Hemel Hempstead",
    postcodes: ["HP1", "HP2", "HP3"],
    description: "Our home base. Mobile mechanic services throughout Hemel Hempstead.",
  },
  {
    slug: "watford",
    name: "Watford",
    postcodes: ["WD17", "WD18", "WD19", "WD23", "WD24", "WD25"],
    description: "Mobile mechanic services throughout Watford and surrounding areas.",
  },
  {
    slug: "st-albans",
    name: "St Albans",
    postcodes: ["AL1", "AL2", "AL3", "AL4"],
    description: "Mobile mechanic services across St Albans.",
  },
  {
    slug: "luton",
    name: "Luton",
    postcodes: ["LU1", "LU2", "LU3", "LU4", "LU5", "LU6", "LU7"],
    description: "Mobile mechanic services in Luton and nearby areas.",
  },
  {
    slug: "dunstable",
    name: "Dunstable",
    postcodes: ["LU5", "LU6"],
    description: "Mobile mechanic services throughout Dunstable.",
  },
  {
    slug: "milton-keynes",
    name: "Milton Keynes",
    postcodes: ["MK1", "MK2", "MK3", "MK4", "MK5", "MK6", "MK7", "MK8", "MK9", "MK10", "MK11", "MK12", "MK13", "MK14", "MK15"],
    description: "Mobile mechanic services across Milton Keynes.",
  },
  {
    slug: "aylesbury",
    name: "Aylesbury",
    postcodes: ["HP17", "HP18", "HP19", "HP20", "HP21", "HP22"],
    description: "Mobile mechanic services covering Aylesbury and the Vale.",
  },
  {
    slug: "stevenage",
    name: "Stevenage",
    postcodes: ["SG1", "SG2"],
    description: "Mobile mechanic services throughout Stevenage.",
  },
  {
    slug: "hatfield",
    name: "Hatfield",
    postcodes: ["AL9", "AL10"],
    description: "Mobile mechanic services in Hatfield.",
  },
  {
    slug: "north-london",
    name: "North London",
    postcodes: ["N1", "N2", "N3", "N4", "N5", "N6", "N7", "N8", "N9", "N10", "N11", "N12", "N13", "N14", "N15", "N16", "N17", "N18", "N19", "N20", "N21", "N22", "EN1", "EN2", "EN3", "EN4", "EN5"],
    description: "Mobile mechanic services across North London and Enfield areas.",
  },
] as const;